### ISSUE TITLE
关于最新版toolbox对mc检测

### ISSUE THREAD

**Issue by liuyuan6666** [Xposed-Modules-Repo/com.luckyzyx.toolboxunlock#2]
最新版Toolbox针对mc进行检测，非谷歌商店下载安装的mc无法使用tb

新版本的tb对MC进行了限制，检测了MC使用的安装器，不是谷歌商店安装的就无法使用。b站up主泥土NITU给出了解决方法，不知道作者能否看一下新版能不能加入一下。
1.找到io/mrarm/mctoolbox/MinecraftActivity类

2.onCreate方法内在第一行添加:
invoke-virtual {p0}, Lio/mrarm/mctoolbox/MinecraftActivity;->fix()V

3.添加一个fix方法:
.method public fix()V
.registers 4
invoke-static {p0}, Landroid/preference/PreferenceManager;->getDefaultSharedPreferences(Landroid/content/Context;)Landroid/content/SharedPreferences;
move-result-object v0
invoke-interface {v0}, Landroid/content/SharedPreferences;->edit()Landroid/content/SharedPreferences$Editor;
move-result-object v0
const-string v1, "test"
const-string v2, "0"
invoke-interface {v0, v1, v2}, Landroid/content/SharedPreferences$Editor;->putString(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;
move-result-object v0
invoke-interface {v0}, Landroid/content/SharedPreferences$Editor;->apply()V
return-void
.end method

**Comment by luckyzyx** [comment]
已发布v1.3
https://github.com/Xposed-Modules-Repo/com.luckyzyx.toolboxunlock/releases/tag/91-1.3
