### ISSUE TITLE
lsp模块为测试的最新1.92（7058）但模块不起作用

### ISSUE THREAD

**Issue by liuyuan6666** [Xposed-Modules-Repo/com.luckyzyx.toolboxunlock#3]
如题一直提示模块未激活弹窗，未开启API调用保护
![Screenshot_2024-02-21-21-47-10-662_com.luckyzyx.toolboxunlock.jpg](https://github.com/Xposed-Modules-Repo/com.luckyzyx.toolboxunlock/assets/105497675/d2924192-7990-4f22-9b9d-754304e358a0)

**Comment by liuyuan6666** [comment]
🤣坏了，模块更新后要重新开关一次作用域。我还奇怪怎么一直重启

**Comment by liuyuan6666** [comment]
而且重启作用域后打开去除签名验证的时候，还得将box杀死一次。首次操作需要处理一下，后续就没出现问题了

**Comment by luckyzyx** [comment]
Hook生效就是需要杀死作用域啊

**Comment by liuyuan6666** [comment]
> Hook生效就是需要杀死作用域啊

是我没表达清楚，被hook的软件。哪怕后台没运行也需要启动然后杀一次后台，然后模块要重启一次作用域（停用模块然后再次启用）

**Comment by luckyzyx** [comment]
> > Hook生效就是需要杀死作用域啊
> 
> 是我没表达清楚，被hook的软件。哪怕后台没运行也需要启动然后杀一次后台，然后模块要重启一次作用域（停用模块然后再次启用）

应该是Hook缓存问题，不过能用了就行（）
